import * as THREE from './vendor/three.module.min.js';

const $=s=>document.querySelector(s),canvas=$('#game');
const qaTarget=Math.max(0,Number(new URLSearchParams(location.search).get('qa')||0)),qaMode=qaTarget>0;
let W=innerWidth,H=innerHeight,last=0,state='menu',distance=0,shots=0,speed=17,spawnAt=25;
let lane=1,laneX=0,jumpY=0,jumpV=0,slide=0,segmentDistance=0,turning=false,turnT=0,turnDir=1,turnChoice=0;
let obstacles=[],pickups=[],powerups=[],roadTiles=[],cityBlocks=[],junction=null;
let combo=1,comboClock=0,nearMisses=0,jumps=0,shield=0,magnet=0,boost=0,chasePressure=0,districtIndex=-1,missionIndex=0,missionProgress=0,currentLevel=1,levelFlash=0;
let countdownToken=0,nextApeCall=9;
let qaStats={collisions:0,jumps:0,slides:0,laneChanges:0,turns:0,started:0};
const lanes=[-2.25,0,2.25];
const districts=[{name:'DOWNTOWN',fog:0x59605f,exposure:1.16,tint:0xffffff},{name:'WAREHOUSE',fog:0x4b403b,exposure:1.05,tint:0xd9b18d},{name:'RIVERFRONT',fog:0x3c5964,exposure:1.28,tint:0xaad7e8},{name:'NORTH LOOP',fog:0x4b505c,exposure:1.1,tint:0xd8e2f0}];
const missions=[{label:'COLLECT 8 FENT',goal:8,type:'collect'},{label:'JUMP 4 OBSTACLES',goal:4,type:'jump'},{label:'GET 3 NEAR MISSES',goal:3,type:'near'}];
const outfits=[{name:'NIGHT',unlock:0,color:0xffffff},{name:'EMBER',unlock:300,color:0xffb07b},{name:'NEON',unlock:700,color:0x8dffff}];
let bestDistance=Number(localStorage.getItem('breathingBest')||0),outfitIndex=Math.min(Number(localStorage.getItem('breathingOutfit')||0),outfits.filter(o=>o.unlock<=bestDistance).length-1);
let reducedMotion=localStorage.getItem('breathingReducedMotion')==='1';
let vibration=localStorage.getItem('breathingVibration')!=='0',queuedAction='',queuedActionUntil=0,officerJumpDelay=0,officerJump=0,jumpWindow=0;
let cleanRunSeconds=0;
let totalFent=Number(localStorage.getItem('breathingTotalFent')||0),tutorialSeen=localStorage.getItem('breathingTutorial')==='1';
let bestClean=Number(localStorage.getItem('breathingBestClean')||0),currentClean=0;
const achievementDefs=[{id:'escape',name:'FIRST ESCAPE'},{id:'collector',name:'COLLECTOR · 50 FENT'},{id:'distance',name:'DISTANCE · 500M'},{id:'corner',name:'STREETWISE · FIRST TURN'}];
let achievements=JSON.parse(localStorage.getItem('breathingAchievements')||'{}');

const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.shadowMap.enabled=false;
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.16;
function skyTexture(){const c=document.createElement('canvas');c.width=32;c.height=512;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,512);g.addColorStop(0,'#293b49');g.addColorStop(.45,'#7c8583');g.addColorStop(.72,'#c57d57');g.addColorStop(1,'#23282a');x.fillStyle=g;x.fillRect(0,0,32,512);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
const scene=new THREE.Scene();scene.background=skyTexture();scene.fog=new THREE.FogExp2(0x59605f,.017);
const world=new THREE.Group();scene.add(world);
const cameraRig=new THREE.Group();scene.add(cameraRig);
const camera=new THREE.PerspectiveCamera(63,1,.1,240);camera.position.set(0,5.3,10.5);camera.lookAt(0,1,-8);cameraRig.add(camera);
scene.add(new THREE.HemisphereLight(0xb9d0d2,0x251d18,2.2));
const sun=new THREE.DirectionalLight(0xffb889,3.4);sun.position.set(-8,16,7);scene.add(sun);

const mat=(color,rough=.85,emissive=0)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.05,emissive,emissiveIntensity:emissive?1.2:0});
function asphaltMaterial(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#292c2d';x.fillRect(0,0,256,256);for(let i=0;i<2500;i++){const v=35+Math.random()*28;x.fillStyle=`rgb(${v},${v},${v})`;x.fillRect(Math.random()*256,Math.random()*256,1+Math.random()*2,1+Math.random()*2);}for(let i=0;i<7;i++){x.strokeStyle='#17191a';x.lineWidth=1;x.beginPath();let px=Math.random()*256,py=Math.random()*256;x.moveTo(px,py);for(let j=0;j<5;j++){px+=(Math.random()-.5)*28;py+=10+Math.random()*16;x.lineTo(px,py);}x.stroke();}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1,4);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map:t,color:0xffffff,roughness:.96});}
function facadeMaterial(seed){const c=document.createElement('canvas');c.width=256;c.height=512;const x=c.getContext('2d'),bases=['#32383a','#4b4541','#30383b','#493f3a'];x.fillStyle=bases[seed%bases.length];x.fillRect(0,0,256,512);for(let i=0;i<1800;i++){x.fillStyle=`rgba(0,0,0,${Math.random()*.12})`;x.fillRect(Math.random()*256,Math.random()*512,1+Math.random()*4,1+Math.random()*6);}for(let yy=40;yy<480;yy+=76)for(let xx=26;xx<240;xx+=58){const lit=Math.random()<.23;x.fillStyle=lit?'#c95f37':'#111719';x.fillRect(xx,yy,27,39);x.fillStyle=lit?'#ffb35b55':'#ffffff08';x.fillRect(xx+3,yy+3,21,4);}x.fillStyle='#1118';x.fillRect(0,455,256,57);if(seed%3===0){x.font='900 25px Arial';x.fillStyle='#d15b37aa';x.fillText('BREATHE',22,487);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;return new THREE.MeshStandardMaterial({map:t,roughness:.9});}
const facadeAtlas=new THREE.TextureLoader().load('./assets/city-facades.png');facadeAtlas.colorSpace=THREE.SRGBColorSpace;facadeAtlas.wrapS=THREE.RepeatWrapping;facadeAtlas.anisotropy=renderer.capabilities.getMaxAnisotropy();
const facades=[0,1,2,3].map(i=>{const t=facadeAtlas.clone();t.needsUpdate=true;t.repeat.set(.25,1);t.offset.set(i*.25,0);return new THREE.MeshStandardMaterial({map:t,roughness:.86,metalness:.04});});
const asphalt=asphaltMaterial(),stripe=mat(0xd8d1b5),concrete=mat(0x686b67),dark=mat(0x24201e),fur=mat(0x302824),furLight=mat(0x51443b),skin=mat(0x796451),blue=mat(0x28d8ff,.2,0x075b70),orange=mat(0xe65d27,.65,0x57200e);
function box(w,h,d,m,x=0,y=0,z=0){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(x,y,z);q.castShadow=q.receiveShadow=true;return q;}
function sphere(r,m,x=0,y=0,z=0){const q=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),m);q.position.set(x,y,z);q.castShadow=true;return q;}
function ellipsoid(xr,yr,zr,m,x=0,y=0,z=0){const q=sphere(1,m,x,y,z);q.scale.set(xr,yr,zr);return q;}
function limb(top,bottom,len,m,x,y,z){const q=new THREE.Mesh(new THREE.CylinderGeometry(bottom,top,len,10),m);q.position.set(x,y,z);return q;}
function signMaterial(lines){
  const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');x.fillStyle='#c6a66c';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#4b2d1e';x.lineWidth=18;x.strokeRect(9,9,c.width-18,c.height-18);x.fillStyle='#24170f';x.textAlign='center';x.textBaseline='middle';x.font='900 67px Inter, Arial, sans-serif';
  lines.forEach((line,i)=>x.fillText(line,256,82+i*92));const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();return new THREE.MeshBasicMaterial({map:texture});
}

function makeGorilla(scale=1){
  const g=new THREE.Group(),torso=ellipsoid(.72*scale,.88*scale,.5*scale,fur,0,1.35*scale,0),head=ellipsoid(.42*scale,.48*scale,.38*scale,fur,0,2.18*scale,.02),muzzle=ellipsoid(.29*scale,.2*scale,.2*scale,furLight,0,2.05*scale,.34);g.add(torso,head,muzzle);
  g.add(sphere(.13*scale,fur,-.38*scale,2.23*scale,0),sphere(.13*scale,fur,.38*scale,2.23*scale,0));
  const armL=limb(.13*scale,.2*scale,1.25*scale,fur,-.7*scale,1.14*scale,0),armR=armL.clone();armR.position.x=.7*scale;armL.rotation.z=-.2;armR.rotation.z=.2;g.add(armL,armR);g.add(ellipsoid(.24*scale,.15*scale,.25*scale,furLight,-.82*scale,.48*scale,.08),ellipsoid(.24*scale,.15*scale,.25*scale,furLight,.82*scale,.48*scale,.08));
  const legL=limb(.17*scale,.22*scale,.72*scale,fur,-.3*scale,.48*scale,0),legR=legL.clone();legR.position.x=.3*scale;g.add(legL,legR);g.add(ellipsoid(.25*scale,.12*scale,.35*scale,furLight,-.3*scale,.1*scale,.12),ellipsoid(.25*scale,.12*scale,.35*scale,furLight,.3*scale,.1*scale,.12));g.userData={armL,armR,legL,legR,head,torso,torsoBaseY:1.35*scale,headBaseY:2.18*scale};return g;
}
function makeOfficer(){
  const g=new THREE.Group(),uniform=mat(0x315b83),gold=mat(0xd8ba43,.35,0x413200),officerSkin=mat(0xe2b18e),blonde=mat(0xd7b45e),torso=ellipsoid(.44,.68,.28,uniform,0,1.35,0),head=ellipsoid(.28,.33,.27,officerSkin,0,2.1,0);g.add(torso,head);
  const hair=ellipsoid(.3,.2,.29,blonde,0,2.26,-.03),leftHair=ellipsoid(.075,.18,.09,blonde,-.25,2.18,.02),rightHair=leftHair.clone();rightHair.position.x=.25;g.add(hair,leftHair,rightHair);
  const cap=new THREE.Mesh(new THREE.CylinderGeometry(.32,.36,.13,16),dark);cap.position.set(0,2.38,0);g.add(cap,box(.42,.06,.25,dark,0,2.32,.18),box(.13,.16,.05,gold,0,1.48,.3));const armL=limb(.09,.11,.88,uniform,-.48,1.3,0),armR=armL.clone();armR.position.x=.48;const legL=limb(.11,.15,.9,dark,-.2,.48,0),legR=legL.clone();legR.position.x=.2;g.add(armL,armR,legL,legR);g.userData={armL,armR,legL,legR};return g;
}
const gorillaTexture=new THREE.TextureLoader().load('./assets/gorilla-run.png');gorillaTexture.colorSpace=THREE.SRGBColorSpace;gorillaTexture.wrapS=THREE.RepeatWrapping;gorillaTexture.repeat.set(.25,1);gorillaTexture.offset.set(0,0);
const player=new THREE.Group(),gorillaSprite=new THREE.Mesh(new THREE.PlaneGeometry(2.2,3.5),new THREE.MeshBasicMaterial({map:gorillaTexture,transparent:true,alphaTest:.025,side:THREE.DoubleSide,depthWrite:true,toneMapped:false}));gorillaSprite.position.y=1.58;player.add(gorillaSprite);player.userData={sprite:gorillaSprite,texture:gorillaTexture,lastFrame:-1};player.position.set(0,0,3.2);scene.add(player);
const shadowMat=new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.38,depthWrite:false}),playerShadow=new THREE.Mesh(new THREE.CircleGeometry(.72,24),shadowMat);playerShadow.rotation.x=-Math.PI/2;playerShadow.scale.y=.5;playerShadow.position.set(0,.025,3.2);scene.add(playerShadow);
const officerTexture=new THREE.TextureLoader().load('./assets/officer-run-back.png');officerTexture.colorSpace=THREE.SRGBColorSpace;officerTexture.wrapS=THREE.RepeatWrapping;officerTexture.repeat.set(.25,1);officerTexture.offset.set(0,0);
const officer=new THREE.Group(),officerSprite=new THREE.Mesh(new THREE.PlaneGeometry(1.65,2.65),new THREE.MeshBasicMaterial({map:officerTexture,transparent:true,alphaTest:.025,side:THREE.DoubleSide,depthWrite:true,toneMapped:false})),officerShadow=new THREE.Mesh(new THREE.CircleGeometry(.48,20),shadowMat.clone());officerSprite.position.y=1.22;officerShadow.rotation.x=-Math.PI/2;officerShadow.scale.y=.45;officerShadow.position.y=.025;officer.add(officerShadow,officerSprite);officer.userData={sprite:officerSprite,texture:officerTexture,lastFrame:-1};officer.position.set(0,0,5.05);scene.add(officer);

function addRoad(z){
  const g=new THREE.Group();g.position.z=z;g.add(box(8,.16,12,asphalt,0,-.1,0),box(2.2,.28,12,concrete,-5.1,.02,0),box(2.2,.28,12,concrete,5.1,.02,0),box(.22,.42,12,mat(0x8a8780),-4.08,.08,0),box(.22,.42,12,mat(0x8a8780),4.08,.08,0),box(.22,.025,12,mat(0x171a1b),-3.82,.01,0),box(.22,.025,12,mat(0x171a1b),3.82,.01,0));
  g.add(box(.07,.025,12,mat(0xc9bf98),-3.55,.012,0),box(.07,.025,12,mat(0xc9bf98),3.55,.012,0));
  for(const x of [-1.15,1.15])for(const zz of [-4.2,1.1,6.35])g.add(box(.09,.03,2.5,stripe,x,.01,zz));
  if(Math.abs(z%48)<1){for(let x=-3.2;x<=3.2;x+=.8)g.add(box(.48,.028,1.55,stripe,x,.012,-4.9));}
  const puddle=new THREE.Mesh(new THREE.CircleGeometry(.45+Math.random()*.55,18),new THREE.MeshPhysicalMaterial({color:0x17262d,roughness:.08,metalness:.35,transparent:true,opacity:.55}));puddle.rotation.x=-Math.PI/2;puddle.scale.x=1.8;puddle.position.set((Math.random()-.5)*5.5,.015,(Math.random()-.5)*8);g.add(puddle);
  if(Math.random()<.55){const cover=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.035,22),mat(0x202526,.55));cover.position.set((Math.random()<.5?-1:1)*(1.7+Math.random()),.005,(Math.random()-.5)*6);for(let i=-2;i<=2;i++)cover.add(box(.55,.012,.025,mat(0x565b5c),0,.02,i*.12));g.add(cover);}
  if(Math.random()<.7){const patch=box(1.2+Math.random()*1.5,.018,1.1+Math.random()*2,mat(0x202324),(Math.random()-.5)*4.5,.006,(Math.random()-.5)*7);patch.rotation.y=(Math.random()-.5)*.35;g.add(patch);}
  for(let i=0;i<2;i++){const skid=box(.055,.012,2.8+Math.random()*2,mat(0x101112),(-.7+i*1.4)+(Math.random()-.5)*.4,.008,(Math.random()-.5)*6);skid.rotation.y=(Math.random()-.5)*.18;g.add(skid);}
  if(Math.random()<.65){const drain=box(.42,.025,.68,mat(0x1d2223,.5),Math.random()<.5?-3.45:3.45,.018,(Math.random()-.5)*8);for(let i=-2;i<=2;i++)drain.add(box(.32,.015,.025,mat(0x606667),0,.02,i*.11));g.add(drain);}
  world.add(g);roadTiles.push(g);
}
function addBlock(side,z){
  const g=new THREE.Group(),x=side*(6.8+Math.random()*2),h=4+Math.random()*9,w=3.5+Math.random()*3.5,facade=facades[Math.floor(Math.random()*facades.length)];
  g.position.set(x,0,z);g.add(box(w,h,5,facade,0,h/2,0));
  const fire=Math.random()<.38;if(fire)g.add(box(.7,1,.1,orange,-side*w*.51,1.1,1));
  const streetX=-side*(w*.5+.55),shop=box(Math.min(2.7,w*.72),1.55,.12,mat(0x111313),-side*w*.505,1.05,.65);g.add(shop);
  const awning=box(Math.min(2.9,w*.76),.12,.85,mat([0x6f2924,0x263d55,0x574b2c][Math.floor(Math.random()*3)]),-side*(w*.5+.35),1.82,.65);awning.rotation.z=side*.08;g.add(awning);
  for(let floor=2.5;floor<h-.5;floor+=1.65)g.add(box(.16,.09,4.4,mat(0x77736c),-side*w*.51,floor,0));
  for(let i=-1;i<=1;i++){const board=box(.16,1.85,.14,mat(0x755133),-side*w*.52+i*.62,.98,.72);board.rotation.z=(i*.12)+.08;g.add(board);}
  for(let i=0;i<3;i++){const shard=box(.12+Math.random()*.2,.025,.22+Math.random()*.35,mat(0x83a7ad,.2,0x102428),streetX-side*Math.random(),.19,(Math.random()-.5)*2.8);shard.rotation.y=Math.random()*3;g.add(shard);}
  if(Math.random()<.55){const bin=box(.75,.78,.72,mat(0x30483a),streetX-side*.7,.43,-1.2);bin.rotation.z=side*(Math.random()<.65?1.3:.15);g.add(bin);}
  if(Math.random()<.48){for(let i=0;i<3;i++){const loot=box(.34+Math.random()*.35,.18+Math.random()*.22,.35+Math.random()*.3,mat([0x7d3430,0x375273,0xa58b54][i]),streetX-side*(.3+i*.35),.22,(i-1)*.55);loot.rotation.y=i*.7;g.add(loot);}}
  if(fire){const smokeMat=new THREE.MeshBasicMaterial({color:0x292a2b,transparent:true,opacity:.24,depthWrite:false});for(let i=0;i<3;i++)g.add(ellipsoid(.3+i*.1,.38+i*.12,.3+i*.1,smokeMat,-side*w*.5,2+i*.62,1));}
  if(Math.random()<.45){const sign=box(.12,.65,1.35,mat(0x172329,.45,0x12313a),-side*(w*.5+.12),2.25,-.7);sign.rotation.z=side*(Math.random()-.5)*.12;g.add(sign);}
  const pole=new THREE.Mesh(new THREE.CylinderGeometry(.04,.055,2.5,8),dark);pole.position.set(-side*(w*.5+1.25),1.25,1.2);const lamp=ellipsoid(.16,.1,.16,mat(0xffb25d,.25,0x8a3d12),pole.position.x,2.48,1.2);g.add(pole,lamp);for(let i=0;i<3;i++){const debris=box(.12+Math.random()*.28,.08,.16+Math.random()*.3,mat(0x332a24),-side*(w*.5+1+Math.random()*1.5),.2,(Math.random()-.5)*3);debris.rotation.y=Math.random()*3;g.add(debris);}
  world.add(g);cityBlocks.push(g);
}
function buildWorld(){
  for(const x of [...roadTiles,...cityBlocks,...obstacles,...pickups,...powerups])world.remove(x);roadTiles=[];cityBlocks=[];obstacles=[];pickups=[];powerups=[];
  for(let z=120;z>-156;z-=12)addRoad(z);for(let z=5;z>-145;z-=14){addBlock(-1,z);addBlock(1,z-6);}
  for(let d=25;d<135;d+=25)spawnChallenge(-d);
}
function resetSegmentObjects(){for(const x of [...obstacles,...pickups,...powerups])world.remove(x);obstacles=[];pickups=[];powerups=[];for(let d=25;d<135;d+=25)spawnChallenge(-d);}
function monkeyObstacle(x,z){
  const g=makeGorilla(.48),messages=[['APE','RIGHTS'],['NO','CAGES'],['APES','UNITED'],['LET APES','LIVE'],['FREEDOM','FOR APES']],wording=messages[Math.floor(Math.random()*messages.length)];g.position.set(x,0,z);const sign=box(1.8,.92,.09,mat(0xb99a5d),0,2.05,.14);const face=new THREE.Mesh(new THREE.PlaneGeometry(1.72,.84),signMaterial(wording));face.position.set(0,2.05,.191);g.add(sign,face);world.add(g);obstacles.push(Object.assign(g,{kind:'jump',hit:false}));
}
const urbanAtlas=new THREE.TextureLoader().load('./assets/urban-obstacles.png');urbanAtlas.colorSpace=THREE.SRGBColorSpace;urbanAtlas.wrapS=THREE.RepeatWrapping;urbanAtlas.anisotropy=renderer.capabilities.getMaxAnisotropy();
const urbanMaterials=[0,1,2,3].map(i=>{const t=urbanAtlas.clone();t.needsUpdate=true;t.repeat.set(.25,1);t.offset.set(i*.25,0);return new THREE.MeshBasicMaterial({map:t,transparent:true,alphaTest:.025,side:THREE.DoubleSide,depthWrite:true,toneMapped:false});});
const gantryTexture=new THREE.TextureLoader().load('./assets/overhead-gantry.png');gantryTexture.colorSpace=THREE.SRGBColorSpace;gantryTexture.anisotropy=renderer.capabilities.getMaxAnisotropy();const gantryMaterial=new THREE.MeshBasicMaterial({map:gantryTexture,transparent:true,alphaTest:.025,side:THREE.DoubleSide,depthWrite:true,toneMapped:false});
function renderedObstacle(x,z,index,kind,w,h){const g=new THREE.Group(),sprite=new THREE.Mesh(new THREE.PlaneGeometry(w,h),urbanMaterials[index]),shadow=new THREE.Mesh(new THREE.CircleGeometry(w*.34,20),shadowMat.clone());g.position.set(x,0,z);sprite.position.y=h*.47;shadow.rotation.x=-Math.PI/2;shadow.scale.y=.45;shadow.position.y=.025;g.add(shadow,sprite);g.userData.sprite=sprite;world.add(g);obstacles.push(Object.assign(g,{kind,hit:false}));}
function barrier(x,z){renderedObstacle(x,z,0,'jump',2.15,1.55);}
function overhead(x,z){const g=new THREE.Group(),sprite=new THREE.Mesh(new THREE.PlaneGeometry(2.55,2.65),gantryMaterial),shadow=new THREE.Mesh(new THREE.CircleGeometry(.95,20),shadowMat.clone());g.position.set(x,0,z);sprite.position.y=1.25;shadow.rotation.x=-Math.PI/2;shadow.scale.y=.5;shadow.position.y=.025;g.add(shadow,sprite);g.userData.sprite=sprite;world.add(g);obstacles.push(Object.assign(g,{kind:'slide',hit:false}));}
function fire(x,z){renderedObstacle(x,z,3,'dodge',2.45,1.62);}
function overturnedCar(x,z){renderedObstacle(x,z,2,'dodge',2.65,1.78);}
function dumpster(x,z){renderedObstacle(x,z,1,'jump',2.25,1.72);}
function syringe(x,z){
  const g=new THREE.Group();g.position.set(x,1.05,z);g.rotation.z=-.25;
  const glass=new THREE.MeshPhysicalMaterial({color:0xe8f6f8,transparent:true,opacity:.5,roughness:.08,transmission:.25,depthWrite:false});
  const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,1.05,16,1,true),glass);barrel.rotation.z=Math.PI/2;g.add(barrel);
  const fluid=new THREE.Mesh(new THREE.CylinderGeometry(.105,.105,.72,14),blue);fluid.rotation.z=Math.PI/2;fluid.position.x=.08;g.add(fluid);
  const plunger=box(.62,.065,.065,stripe,-.78,0,0),thumb=box(.08,.52,.12,stripe,-1.08,0,0),flange=box(.08,.58,.12,stripe,-.5,0,0);g.add(plunger,thumb,flange);
  const hub=new THREE.Mesh(new THREE.CylinderGeometry(.1,.15,.22,12),mat(0xdde7e8));hub.rotation.z=Math.PI/2;hub.position.x=.64;g.add(hub);
  const needle=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,.76,8),mat(0xbfc8c9,.2));needle.rotation.z=Math.PI/2;needle.position.x=1.12;g.add(needle);
  const tip=new THREE.Mesh(new THREE.ConeGeometry(.025,.16,8),mat(0xdde4e5,.15));tip.rotation.z=-Math.PI/2;tip.position.x=1.58;g.add(tip);
  g.scale.setScalar(.72);world.add(g);pickups.push(g);
}
function powerUp(x,z,kind){const g=new THREE.Group(),color=kind==='shield'?0x56d8ff:0xffd84c,m=mat(color,.2,color===0x56d8ff?0x124c66:0x665000);g.position.set(x,1.35,z);const core=sphere(.38,m),ring=new THREE.Mesh(new THREE.TorusGeometry(.62,.09,8,24),m);ring.rotation.x=Math.PI/2;g.add(core,ring);g.userData.kind=kind;world.add(g);powerups.push(g);}
function spawnChallenge(z){
  const safe=Math.floor(Math.random()*3),blocked=[0,1,2].filter(i=>i!==safe),count=Math.random()<(currentLevel<3?.65:.28)?1:2;
  blocked.slice(0,count).forEach((li,i)=>{let r=(Math.random()+districtIndex*.11)%1;(r<.2?monkeyObstacle:r<.38?barrier:r<.54?overhead:r<.7?fire:r<.86?overturnedCar:dumpster)(lanes[li],z-i*.3);});
  for(let i=0;i<3;i++)syringe(lanes[safe],z+5-i*3.4);
  if(Math.random()<.14)powerUp(lanes[safe],z-5,Math.random()<.5?'shield':'magnet');
}
function makeJunction(){
  if(junction)world.remove(junction);junction=new THREE.Group();junction.position.z=-58;
  const crossRoad=box(74,.18,9,asphalt,0,-.08,0),farSidewalk=box(74,.3,2,concrete,0,.02,-5.05);junction.add(crossRoad,farSidewalk);for(let x=-34;x<=34;x+=4.5){junction.add(box(2.4,.025,.09,stripe,x,.015,-1.55),box(2.4,.025,.09,stripe,x,.015,1.55));}for(let x=-3.4;x<=3.4;x+=.85)junction.add(box(.5,.028,1.45,stripe,x,.018,3.25));
  for(const side of [-1,1])for(let i=0;i<4;i++){const bx=side*(10+i*7.4),h=5.5+Math.random()*6,w=5.7+Math.random()*1.2;const front=box(w,h,5,facades[(i+(side>0?1:3))%facades.length],bx,h/2,-7.1),back=box(w,h*.88,5,facades[(i+2)%facades.length],bx,h*.44,7.1);junction.add(front,back);}
  const endCap=new THREE.Group(),centerBuilding=box(8.8,10.8,5.2,facades[2],0,5.4,-7.35),leftBuilding=box(5.8,8.2,5.2,facades[0],-7.25,4.1,-7.35),rightBuilding=box(5.8,8.8,5.2,facades[3],7.25,4.4,-7.35);endCap.add(centerBuilding,leftBuilding,rightBuilding,box(7.2,1.7,.18,mat(0x111416),0,1.1,-4.68),box(2.7,.15,1,mat(0x6f2924),-5.7,2.05,-4.55),box(2.7,.15,1,mat(0x263d55),5.7,2.05,-4.55));junction.add(endCap);
  const roll=Math.random(),allowed=roll<.25?[-1]:roll<.5?[1]:[-1,1];
  for(const dir of [-1,1])if(!allowed.includes(dir)){const closureX=dir*11.5;for(let i=-1;i<=1;i++){const barrier=box(1.65,.72,.32,mat(i===0?0xe9e4d1:0xd3542b),closureX+i*1.7,.42,0);barrier.rotation.y=.04*i;junction.add(barrier);}const wreck=box(2.4,.9,1.35,mat(0x34393a),closureX-dir*1.4,.47,-1.7);wreck.rotation.y=dir*.2;junction.add(wreck);}
  for(const dir of allowed){for(let i=0;i<3;i++){const lamp=new THREE.Mesh(new THREE.CylinderGeometry(.035,.05,2.2,7),dark);lamp.position.set(dir*(5.2+i*4),1.1,-3);junction.add(lamp,ellipsoid(.14,.09,.14,mat(0xffb55c,.25,0x633210),lamp.position.x,2.18,-3));}}
  const signalDark=mat(0x171a1b),signalRed=mat(0xff3b24,.2,0x8f1008);for(const x of [-4.35,4.35]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,3.8,8),signalDark);pole.position.set(x,1.9,3.15);const arm=box(3.2,.1,.1,signalDark,x>0?-1.55:1.55,3.72,0);arm.position.x=x+(x>0?-1.55:1.55);arm.position.z=3.15;const head=box(.62,1.25,.42,signalDark,x+(x>0?-3:3),3.28,3.15),red=ellipsoid(.18,.18,.08,signalRed,head.position.x,3.58,3.38);junction.add(pole,arm,head,red);}
  for(let x=-3.25;x<=3.25;x+=.72)junction.add(box(.46,.03,1.7,stripe,x,.02,3.25));
  junction.userData={crossRoad,allowed,wallLocalZ:-4.7};turnChoice=0;$('#turn-arrow').textContent=allowed.length===2?'↔':allowed[0]===-1?'←':'→';$('#turn-warning').classList.remove('visible','selected');world.add(junction);
}

// Compact procedural sound layer.
const audio={ctx:null,master:null,music:null,sfx:null,ape:null,muted:false,beat:0,next:0,apeBuffer:null,apeLoading:false};
function loadApeRecording(){if(!audio.ctx||audio.apeBuffer||audio.apeLoading)return;audio.apeLoading=true;fetch('./assets/vervet-monkey-calls.mp3').then(r=>{if(!r.ok)throw new Error('ape audio unavailable');return r.arrayBuffer();}).then(b=>audio.ctx.decodeAudioData(b)).then(b=>{audio.apeBuffer=b;}).catch(()=>{}).finally(()=>{audio.apeLoading=false;});}
function initAudio(){if(audio.ctx){audio.ctx.resume();loadApeRecording();return;}const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio.ctx=new AC();audio.master=audio.ctx.createGain();audio.music=audio.ctx.createGain();audio.sfx=audio.ctx.createGain();audio.ape=audio.ctx.createGain();audio.master.gain.value=.68;audio.music.gain.value=Number(localStorage.getItem('breathingMusic')||42)/210;audio.sfx.gain.value=Number(localStorage.getItem('breathingSfx')||78)/108;audio.ape.gain.value=Number(localStorage.getItem('breathingApe')||85)/100;audio.music.connect(audio.master);audio.sfx.connect(audio.master);audio.ape.connect(audio.master);audio.master.connect(audio.ctx.destination);loadApeRecording();}
function tone(f,d=.1,v=.08,type='square'){if(!audio.ctx||audio.muted)return;const t=audio.ctx.currentTime,o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(audio.sfx);o.start(t);o.stop(t+d);}
function noteAt(f,start,d=.12,v=.04,type='triangle'){const o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,start);g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(v,start+.012);g.gain.exponentialRampToValueAtTime(.001,start+d);o.connect(g);g.connect(audio.music);o.start(start);o.stop(start+d+.01);}
function runnerSoundAt(start,breath=false){const o=audio.ctx.createOscillator(),g=audio.ctx.createGain(),f=audio.ctx.createBiquadFilter();o.type=breath?'sawtooth':'sine';o.frequency.setValueAtTime(breath?118:82,start);o.frequency.exponentialRampToValueAtTime(breath?72:48,start+(breath?.2:.045));f.type='lowpass';f.frequency.value=breath?360:150;g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(breath?.035:.055,start+.012);g.gain.exponentialRampToValueAtTime(.001,start+(breath?.22:.075));o.connect(f);f.connect(g);g.connect(audio.sfx);o.start(start);o.stop(start+(breath?.24:.08));}
function monkeyCall(){if(!audio.ctx||audio.muted||!audio.apeBuffer)return;const t=audio.ctx.currentTime,src=audio.ctx.createBufferSource(),filter=audio.ctx.createBiquadFilter(),g=audio.ctx.createGain(),offsets=[.3,3.8,7.4,11.2,15.1,19.4,23.3,27.5,31.2,34.2],offset=offsets[Math.floor(Math.random()*offsets.length)],musicTarget=Number($('#music-volume').value)/210;src.buffer=audio.apeBuffer;src.playbackRate.value=.94+Math.random()*.12;filter.type='highpass';filter.frequency.value=180;g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.9,t+.035);g.gain.setValueAtTime(.9,t+1.05);g.gain.exponentialRampToValueAtTime(.001,t+1.35);audio.music.gain.cancelScheduledValues(t);audio.music.gain.setValueAtTime(audio.music.gain.value,t);audio.music.gain.linearRampToValueAtTime(.035,t+.04);audio.music.gain.linearRampToValueAtTime(musicTarget,t+1.45);src.connect(filter);filter.connect(g);g.connect(audio.ape);src.start(t,Math.min(offset,Math.max(0,audio.apeBuffer.duration-1.5)),1.4);}
function audioTick(){if(!audio.ctx||audio.muted||state!=='playing')return;const now=audio.ctx.currentTime,step=Math.max(.155,.19-currentLevel*.004),melody=[523.25,659.25,783.99,659.25,587.33,698.46,880,698.46,523.25,659.25,783.99,1046.5,880,783.99,659.25,587.33],bass=[130.81,146.83,174.61,146.83];while(audio.next<now+.08){const b=audio.beat,n=audio.next;if(b%2===0){noteAt(melody[b%melody.length],n,.14,.03,'triangle');runnerSoundAt(n+.045,false);}if(b%4===0)noteAt(bass[Math.floor(b/4)%bass.length],n,.18,.05,'sine');if(b%4===2)noteAt(196,n,.045,.015,'square');if(b%16===14)runnerSoundAt(n,true);audio.beat++;audio.next+=step;}if(distance>=nextApeCall){monkeyCall();nextApeCall=distance+115+Math.random()*135;}}
$('#sound-button').onclick=()=>{initAudio();audio.muted=!audio.muted;audio.master.gain.setTargetAtTime(audio.muted?0:.68,audio.ctx.currentTime,.05);$('#sound-button').textContent=audio.muted?'×':'♪';};
for(const [id,key] of [['music-volume','breathingMusic'],['sfx-volume','breathingSfx'],['ape-volume','breathingApe']]){const el=$('#'+id),saved=localStorage.getItem(key);if(saved!==null)el.value=saved;el.oninput=()=>{localStorage.setItem(key,el.value);if(!audio.ctx)return;if(id==='music-volume')audio.music.gain.setTargetAtTime(Number(el.value)/210,audio.ctx.currentTime,.04);if(id==='sfx-volume')audio.sfx.gain.setTargetAtTime(Number(el.value)/108,audio.ctx.currentTime,.04);if(id==='ape-volume')audio.ape.gain.setTargetAtTime(Number(el.value)/100,audio.ctx.currentTime,.04);};}
$('#vibration-setting').checked=vibration;$('#vibration-setting').onchange=e=>{vibration=e.target.checked;localStorage.setItem('breathingVibration',vibration?'1':'0');};const haptic=(pattern=18)=>{if(vibration&&navigator.vibrate)navigator.vibrate(pattern);};

function applyOutfit(){const o=outfits[outfitIndex];player.userData.sprite.material.color.setHex(o.color);$('#outfit-button').textContent=`PROGRESSION · ${o.name}`;localStorage.setItem('breathingOutfit',outfitIndex);}
function showAchievement(name){const toast=$('#achievement-toast');toast.querySelector('strong').textContent=name;toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),2400);}
function showMove(name,bonus){const toast=$('#move-toast');toast.querySelector('strong').textContent=`${name} · +${bonus}`;toast.classList.add('visible');clearTimeout(showMove.timer);showMove.timer=setTimeout(()=>toast.classList.remove('visible'),900);}
function unlockAchievement(id){if(achievements[id])return;achievements[id]=true;localStorage.setItem('breathingAchievements',JSON.stringify(achievements));showAchievement(achievementDefs.find(a=>a.id===id)?.name||id);}
function refreshProgress(){ $('#meta-best').textContent=`${bestDistance}m`;$('#meta-fent').textContent=totalFent;const list=$('#outfit-list');list.innerHTML='';outfits.forEach((o,i)=>{const unlocked=o.unlock<=bestDistance,b=document.createElement('button');b.className=`outfit-choice ${i===outfitIndex?'selected':''} ${unlocked?'':'locked'}`;b.textContent=unlocked?o.name:`${o.name} · ${o.unlock}M`;b.onclick=()=>{if(!unlocked)return;outfitIndex=i;applyOutfit();refreshProgress();};list.appendChild(b);});const achievementsList=$('#achievement-list');achievementsList.innerHTML='';achievementDefs.forEach(a=>{const d=document.createElement('div');d.className=`achievement ${achievements[a.id]?'done':'locked'}`;d.textContent=`${achievements[a.id]?'✓':'○'} ${a.name}`;achievementsList.appendChild(d);});}
function openProgress(){refreshProgress();$('#meta-clean').textContent=`${Math.floor(bestClean)}m`;$('#start-screen').classList.remove('visible');$('#progress-screen').classList.add('visible');}function closeProgress(){$('#progress-screen').classList.remove('visible');$('#start-screen').classList.add('visible');}
$('#outfit-button').onclick=openProgress;$('#progress-close-button').onclick=closeProgress;applyOutfit();
function setDistrict(force=false){const traveled=Number.isFinite(distance)?Math.max(0,distance):0,next=Math.floor(traveled/350)%districts.length;if(!force&&next===districtIndex)return;districtIndex=next;const d=districts[next]||districts[0];scene.fog.color.setHex(d.fog);renderer.toneMappingExposure=d.exposure;facades.forEach(m=>m.color.setHex(d.tint));asphalt.color.setHex(next===2?0xb8c6ca:next===3?0xc5c9d3:0xffffff);concrete.color.setHex(next===1?0x75655a:next===2?0x68777a:0x686b67);$('#district').textContent=d.name;$('#weather').className=next===1?'embers':next===2?'rain':'';}
function updateLevel(){const next=1+Math.floor(Math.max(0,distance)/500);if(next===currentLevel)return;currentLevel=next;if(currentLevel>=2)unlockAchievement('distance');levelFlash=2.2;$('#level-up strong').textContent=`LEVEL ${currentLevel}`;$('#level-up').classList.add('visible');tone(523.25,.12,.08,'triangle');setTimeout(()=>tone(783.99,.18,.1,'triangle'),120);}
function missionEvent(type,amount=1){const m=missions[missionIndex];if(m.type!==type)return;missionProgress+=amount;if(missionProgress>=m.goal){missionProgress=0;missionIndex=(missionIndex+1)%missions.length;shield=Math.max(shield,6);tone(1046.5,.22,.1,'triangle');}hud();}
function reset(){distance=shots=segmentDistance=0;speed=17;spawnAt=25;nextApeCall=75+Math.random()*80;lane=1;laneX=jumpY=jumpV=slide=jumpWindow=0;turning=false;turnT=0;queuedAction='';queuedActionUntil=officerJumpDelay=officerJump=cleanRunSeconds=0;combo=1;comboClock=nearMisses=jumps=shield=magnet=boost=missionProgress=0;chasePressure=.6;currentLevel=1;levelFlash=0;districtIndex=-1;$('#level-up').classList.remove('visible');$('#turn-warning').classList.remove('visible');$('#turn-mask').classList.remove('active');$('#turn-mask').style.opacity='0';$('#game-shell').classList.remove('boosting','danger','cornering','high-speed');world.position.set(0,0,0);world.rotation.set(0,0,0);cameraRig.rotation.set(0,0,0);cameraRig.position.set(0,0,0);camera.fov=63;camera.updateProjectionMatrix();player.position.set(0,0,3.2);playerShadow.position.set(0,.025,3.2);player.scale.set(1,1,1);player.rotation.set(0,0,0);player.userData.texture.offset.x=0;player.userData.lastFrame=-1;officer.position.set(0,0,5.05);officer.userData.sprite.material.opacity=.6;officerShadow.material.opacity=.23;officer.userData.texture.offset.x=0;officer.userData.lastFrame=-1;if(junction){world.remove(junction);junction=null;}setDistrict(true);buildWorld();hud();}
function startRun(){initAudio();reset();state='countdown';swipeArmed=false;inputUnlockAt=performance.now()+2750;const token=++countdownToken;audio.beat=0;audio.next=audio.ctx?audio.ctx.currentTime+.05:0;document.querySelectorAll('.panel.visible').forEach(p=>p.classList.remove('visible'));document.activeElement?.blur();$('#game-shell').scrollTop=0;const cd=$('#countdown'),value=cd.querySelector('strong');cd.classList.add('visible');['3','2','1','RUN'].forEach((v,i)=>setTimeout(()=>{if(token!==countdownToken)return;value.textContent=v;tone(i===3?784:392+i*65,.1,i===3?.1:.06,'triangle');},i*620));setTimeout(()=>{if(token!==countdownToken)return;cd.classList.remove('visible');lane=1;laneX=0;player.position.x=0;officer.position.x=0;state='playing';unlockAchievement('escape');last=performance.now();},2450);}
function requestStart(){if(tutorialSeen){startRun();return;}$('#start-screen').classList.remove('visible');$('#tutorial-screen').classList.add('visible');}
function over(reason='THE RUN ENDED'){if(state!=='playing')return;state='over';bestDistance=Math.max(bestDistance,Math.floor(distance));localStorage.setItem('breathingBest',bestDistance);$('#game-shell').classList.remove('danger');$('#turn-warning').classList.remove('visible');$('#game-over-reason').textContent=reason==='YOU ARE OUT OF BREATH'?'THE RUN ENDED':reason;$('#final-score').textContent=Math.floor(distance);$('#final-vials').textContent=shots;$('#final-best').textContent=`${bestDistance} m`;setTimeout(()=>{$('#game-over').classList.add('visible');applyOutfit();},250);tone(70,.45,.2,'sawtooth');}
function qaReport(status){let report=$('#qa-report');if(!report){report=document.createElement('div');report.id='qa-report';Object.assign(report.style,{position:'absolute',left:'10px',bottom:'10px',zIndex:'30',padding:'10px',background:'#061117ee',border:'1px solid #45e8ff',color:'#fff',font:'700 10px monospace',whiteSpace:'pre-line',pointerEvents:'none'});$('#game-shell').appendChild(report);}report.textContent=`QA ${status}\n${Math.floor(distance)}m / ${qaTarget}m\nturns ${qaStats.turns} · jumps ${qaStats.jumps} · slides ${qaStats.slides}\nlane changes ${qaStats.laneChanges} · collisions ${qaStats.collisions}`;}
function qaPilot(){if(!qaMode||state!=='playing'||turning)return;if(distance>=qaTarget){state='paused';qaReport('PASSED');return;}if(junction&&junction.position.z>=-38&&!turnChoice){qaStats.turns++;chooseTurn(junction.userData.allowed[Math.floor(Math.random()*junction.userData.allowed.length)]);}const approaching=obstacles.filter(o=>o.position.z>-10&&o.position.z<3.2),current=approaching.find(o=>Math.abs(o.position.x-lanes[lane])<.78),lateJump=new URLSearchParams(location.search).get('timing')==='late',allGround=new URLSearchParams(location.search).get('ground')==='all';if(!current)return;if(current.kind!=='slide'&&(current.kind==='jump'||allGround)&&current.position.z>(lateJump?-3.2:-7)&&jumpY===0){jumpV=12;jumpWindow=.92;officerJumpDelay=.32;qaStats.jumps++;return;}if(current.kind==='slide'&&current.position.z>-6.2&&jumpY===0&&slide===0){slide=.72;qaStats.slides++;return;}if((current.kind==='dodge'&&!allGround)||(current.kind!=='slide'&&jumpY===0&&current.position.z>-.8)||(current.kind==='slide'&&slide===0&&current.position.z>-2)){const free=[0,1,2].filter(li=>!approaching.some(o=>Math.abs(o.position.x-lanes[li])<.78&&Math.abs(o.position.z-current.position.z)<2));if(free.length){lane=free.reduce((a,b)=>Math.abs(b-lane)<Math.abs(a-lane)?b:a,free[0]);qaStats.laneChanges++;}}}
$('#start-button').onclick=requestStart;$('#retry-button').onclick=()=>{currentClean=0;startRun();};$('#tutorial-go-button').onclick=()=>{tutorialSeen=true;currentClean=0;localStorage.setItem('breathingTutorial','1');startRun();};$('#tutorial-skip-button').onclick=()=>{tutorialSeen=true;currentClean=0;localStorage.setItem('breathingTutorial','1');startRun();};
function togglePause(){if(state==='playing'){state='paused';$('#pause-screen').classList.add('visible');$('#pause-button').textContent='▶';}else if(state==='paused'){state='playing';$('#pause-screen').classList.remove('visible');$('#pause-button').textContent='Ⅱ';last=performance.now();}}
$('#pause-button').onclick=togglePause;$('#resume-button').onclick=togglePause;$('#pause-restart-button').onclick=()=>{currentClean=0;startRun();};
function applyMotionSetting(){$('#game-shell').classList.toggle('reduced-motion',reducedMotion);$('#motion-button').textContent=`REDUCED MOTION: ${reducedMotion?'ON':'OFF'}`;}$('#motion-button').onclick=()=>{reducedMotion=!reducedMotion;localStorage.setItem('breathingReducedMotion',reducedMotion?'1':'0');applyMotionSetting();};applyMotionSetting();
function hud(){$('#score').textContent=Math.floor(distance);$('#vials').textContent=shots;$('#level').textContent=`LEVEL ${currentLevel}`;$('#best-score').textContent=`BEST ${Math.max(bestDistance,Math.floor(distance))}m`;$('#combo').textContent=`COMBO ×${combo}`;const m=missions[missionIndex];$('#mission').textContent=`MISSION: ${m.label} · ${missionProgress}/${m.goal}`;const powers=[];if(shield>0)powers.push(`SHIELD ${Math.ceil(shield)}s`);if(magnet>0)powers.push(`MAGNET ${Math.ceil(magnet)}s`);if(boost>0)powers.push(`BOOST ${Math.ceil(boost)}s`);const ps=$('#power-status');ps.textContent=powers.join(' · ');ps.classList.toggle('active',powers.length>0);}

function update(dt){
  if(state!=='playing')return;qaPilot();if(state!=='playing')return;if(!qaMode)audioTick();if(qaMode&&Math.floor(distance)%250===0)qaReport('RUNNING');
  if(turning){distance+=speed*dt*.72;turnT=Math.min(1,turnT+dt/(reducedMotion?.9:1.28));const e=turnT*turnT*turnT*(turnT*(turnT*6-15)+10),angle=turnDir*e*Math.PI/2,pz=3.2,arc=Math.sin(e*Math.PI),runnerArc=Math.sin(e*Math.PI/2);world.rotation.y=angle;world.position.x=-Math.sin(angle)*pz;world.position.z=pz-Math.cos(angle)*pz;cameraRig.rotation.y=reducedMotion?0:-turnDir*arc*.18;cameraRig.rotation.z=reducedMotion?0:-turnDir*arc*.055;cameraRig.position.x=reducedMotion?0:turnDir*arc*.34;cameraRig.position.z=reducedMotion?0:-arc*.22;camera.fov=63+(reducedMotion?0:arc*4.2);camera.updateProjectionMatrix();player.position.x=turnDir*runnerArc*.62;player.position.z=3.2-runnerArc*.18;playerShadow.position.x=player.position.x;playerShadow.position.z=player.position.z;player.rotation.z=-turnDir*arc*.14;officer.position.x+=(player.position.x*.72-officer.position.x)*5*dt;officer.position.y=Math.abs(Math.sin(distance*.38))*.08;animateRunner(dt,true);hud();
    if(turnT>=1){turning=false;turnChoice=0;world.position.set(0,0,0);world.rotation.set(0,0,0);cameraRig.rotation.set(0,0,0);cameraRig.position.set(0,0,0);camera.fov=63;camera.updateProjectionMatrix();player.position.x=0;player.position.z=3.2;playerShadow.position.x=0;playerShadow.position.z=3.2;player.rotation.z=0;segmentDistance=0;spawnAt=25;boost=2.8;combo=Math.min(8,combo+1);comboClock=5;unlockAchievement('corner');showMove('CLEAN CORNER',100);$('#game-shell').classList.remove('cornering');$('#turn-warning').classList.remove('visible','selected');if(junction)world.remove(junction);junction=null;resetSegmentObjects();if(queuedAction&&performance.now()<queuedActionUntil){const q=queuedAction;queuedAction='';setTimeout(()=>act(q),0);}}return;}
  shield=Math.max(0,shield-dt);magnet=Math.max(0,magnet-dt);boost=Math.max(0,boost-dt);comboClock=Math.max(0,comboClock-dt);levelFlash=Math.max(0,levelFlash-dt);$('#game-shell').classList.toggle('boosting',boost>0);if(levelFlash===0)$('#level-up').classList.remove('visible');if(comboClock===0)combo=1;
  updateLevel();speed=Math.min(27,17*Math.pow(1.05,currentLevel-1))+(boost>0?6:0);distance+=speed*dt;segmentDistance+=speed*dt;currentClean+=speed*dt;if(currentClean>bestClean){bestClean=currentClean;localStorage.setItem('breathingBestClean',Math.floor(bestClean));}setDistrict();laneX+=(lanes[lane]-laneX)*Math.min(1,(10+currentLevel*.45)*dt);$('#game-shell').classList.toggle('high-speed',currentLevel>=3&&!reducedMotion);
  jumpWindow=Math.max(0,jumpWindow-dt);jumpV-=30*dt;jumpY+=jumpV*dt;if(jumpY<0){jumpY=0;jumpV=0;}slide=Math.max(0,slide-dt);
  player.position.x=laneX;player.position.y=jumpY;playerShadow.position.x=laneX;playerShadow.material.opacity=.38-Math.min(.28,jumpY*.12);playerShadow.scale.set(1+Math.min(.35,jumpY*.12),.5+Math.min(.2,jumpY*.06),1);player.scale.y+=( (slide>0?.48:1)-player.scale.y)*Math.min(1,15*dt);player.rotation.z+=(0-player.rotation.z)*8*dt;cameraRig.rotation.z+=(((reducedMotion?0:(lanes[lane]-laneX)*-.025))-cameraRig.rotation.z)*5*dt;
  cleanRunSeconds+=dt;if(cleanRunSeconds>5)chasePressure=Math.max(0,chasePressure-dt*.12);officerJumpDelay=Math.max(0,officerJumpDelay-dt);if(officerJumpDelay===0&&officerJump<.01&&jumpY>.4)officerJump=.72;officerJump=Math.max(0,officerJump-dt);const officerLeap=officerJump>0?Math.sin((officerJump/.72)*Math.PI)*.58:0,officerAlpha=Math.min(1,chasePressure*1.35);officer.position.x+=(laneX*.72-officer.position.x)*5*dt;officer.position.z+=((5.1+(1-officerAlpha)*3.6-officerAlpha*.35)-officer.position.z)*3*dt;officer.position.y=Math.abs(Math.sin(distance*.38))*.08+officerLeap;officer.userData.sprite.material.opacity=officerAlpha;officerShadow.material.opacity=.38*officerAlpha;$('#game-shell').classList.toggle('danger',chasePressure>.72);
  const dz=speed*dt;cameraRig.position.y+=( (reducedMotion?0:Math.sin(distance*.72)*(.018+currentLevel*.003))-cameraRig.position.y)*5*dt;for(const r of roadTiles){r.position.z+=dz;if(r.position.z>126)r.position.z-=276;}for(const b of cityBlocks){b.position.z+=dz;if(b.position.z>18)b.position.z-=165;}
  for(const o of obstacles){o.position.z+=dz;if(o.flames)o.flames.forEach((f,i)=>{f.scale.y=.72+Math.sin(distance*.7+i)*.28;f.rotation.y+=dt*(2+i*.2);});if(o.smoke)o.smoke.forEach((s,i)=>{s.position.x=Math.sin(distance*.18+i)*.16;s.material.opacity=.22+Math.sin(distance*.12+i)*.08;});const laneGap=Math.abs(o.position.x-laneX),airborne=jumpWindow>0||jumpY>0,safe=(airborne&&o.kind!=='slide')||(o.kind==='slide'&&slide>0);if(!o.hit&&o.position.z>0&&o.position.z<2.8&&laneGap<.78&&!safe){o.hit=true;currentClean=0;if(qaMode){qaStats.collisions++;qaReport('COLLISION');}haptic([35,35,55]);const shell=$('#game-shell');shell.classList.remove('impact');void shell.offsetWidth;shell.classList.add('impact');setTimeout(()=>shell.classList.remove('impact'),280);player.rotation.z=laneGap<.2?.25:(o.position.x<laneX?.18:-.18);if(shield>0){shield=0;combo=1;tone(180,.18,.1,'square');}else if(chasePressure>.72){combo=1;tone(95,.2,.12,'sawtooth');over('THE OFFICER CAUGHT UP');}else{chasePressure=1;cleanRunSeconds=0;officer.position.z=8.4;combo=1;tone(95,.2,.12,'sawtooth');}}if(!o.userData.passed&&o.position.z>3){o.userData.passed=true;if((laneGap<1.35||safe)&&!o.hit){nearMisses++;combo=Math.min(8,combo+1);comboClock=5;chasePressure=Math.max(0,chasePressure-.08);missionEvent('near');if(safe&&o.kind!=='slide'){jumps++;missionEvent('jump');showMove('PERFECT JUMP',50);}else if(safe&&o.kind==='slide')showMove('CLEAN SLIDE',50);else if(laneGap<1.35)showMove('NEAR MISS',25);tone(740,.08,.045,'triangle');}}}
  for(const p of pickups){p.position.z+=dz;p.rotation.y+=dt*4;p.position.y=1+Math.sin(distance*.2+p.position.z)*.15;if(magnet>0&&p.visible&&p.position.z>-18&&p.position.z<5)p.position.x+=(laneX-p.position.x)*Math.min(1,9*dt);if(p.visible&&p.position.z>0&&p.position.z<2.8&&Math.abs(p.position.x-laneX)<.8){p.visible=false;shots+=combo;totalFent++;localStorage.setItem('breathingTotalFent',totalFent);if(totalFent>=50)unlockAchievement('collector');combo=Math.min(8,combo+1);comboClock=4;missionEvent('collect');tone(880,.11,.1,'sine');hud();}}
  for(const p of powerups){p.position.z+=dz;p.rotation.y+=dt*2.5;if(p.visible&&p.position.z>0&&p.position.z<2.8&&Math.abs(p.position.x-laneX)<.9){p.visible=false;if(p.userData.kind==='shield')shield=10;else magnet=9;tone(660,.22,.11,'triangle');hud();}}
  obstacles=obstacles.filter(o=>{if(o.position.z<14)return true;world.remove(o);return false;});pickups=pickups.filter(p=>{if(p.position.z<14)return true;world.remove(p);return false;});
  powerups=powerups.filter(p=>{if(p.position.z<14)return true;world.remove(p);return false;});
  if(!junction&&segmentDistance>=spawnAt&&segmentDistance<125){spawnChallenge(-120);spawnAt+=25;}
  if(segmentDistance>=195&&!junction)makeJunction();
  if(junction){junction.position.z+=dz;const ready=junction.position.z>=-38;$('#turn-warning').classList.toggle('visible',ready);if(turnChoice&&junction.position.z>=2)beginTurn();else if(!turnChoice&&junction.position.z+junction.userData.wallLocalZ>=1.25)over('MISSED THE TURN');}
  animateRunner(dt,false);hud();
}
function animateRunner(dt,inTurn){
  const cycle=distance*(1.12+currentLevel*.025),s=Math.sin(cycle),frame=Math.floor(distance*(.4+currentLevel*.012))%4,u=player.userData;if(frame!==u.lastFrame){u.texture.offset.x=frame*.25;u.lastFrame=frame;}const airborne=jumpY>0,landing=!airborne&&Math.abs(jumpV)<.01;u.sprite.position.y=1.56+Math.abs(s)*.055+(airborne?.06:0);u.sprite.rotation.z=(inTurn?-turnDir*.055:Math.sin(cycle*.5)*.012);player.scale.x+=( (slide>0?1.12:airborne?.94:1)-player.scale.x)*10*dt;player.rotation.x=airborne?-.055:landing?0:Math.sin(cycle)*.012;player.rotation.y+=( (inTurn?turnDir*.22:0)-player.rotation.y)*7*dt;
  const ou=officer.userData,officerFrame=(frame+2)%4;if(officerFrame!==ou.lastFrame){ou.texture.offset.x=officerFrame*.25;ou.lastFrame=officerFrame;}officer.rotation.z=Math.sin(cycle*1.08)*.018;ou.sprite.position.y=1.21+Math.abs(Math.sin(cycle*1.08))*.035;
}
function beginTurn(){if(!turnChoice||turning)return;turning=true;turnT=0;turnDir=turnChoice;lane=1;laneX=0;$('#turn-warning').classList.remove('visible');$('#game-shell').classList.add('cornering');if(Math.random()<.35)monkeyCall();}
function chooseTurn(dir){if(!junction||turning||turnChoice||junction.position.z<-38)return;if(!junction.userData.allowed.includes(dir)){tone(75,.3,.16,'sawtooth');over('THAT STREET WAS BLOCKED');return;}turnChoice=dir;lane=1;$('#turn-arrow').textContent=dir<0?'←':'→';$('#turn-warning').classList.add('selected');showMove('TURN LOCKED',25);haptic(18);}
function act(dir){if(state!=='playing')return;if(turning){if(dir==='up'||dir==='down'){queuedAction=dir;queuedActionUntil=performance.now()+850;}return;}if((dir==='left'||dir==='right')&&junction&&junction.position.z>=-38){chooseTurn(dir==='left'?-1:1);return;}const oldLane=lane;if(dir==='left'){lane=Math.max(0,lane-1);player.rotation.z=.12;}if(dir==='right'){lane=Math.min(2,lane+1);player.rotation.z=-.12;}if(lane!==oldLane){haptic(12);if(Math.random()<.06)monkeyCall();}if(dir==='up'&&jumpY===0){jumpV=12;jumpWindow=.92;officerJumpDelay=.32;haptic(16);if(Math.random()<.08)monkeyCall();}if(dir==='down'&&jumpY===0){slide=.7;haptic(12);}}
addEventListener('keydown',e=>{const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};if(m[e.key])act(m[e.key]);});
let sx=0,sy=0,swipeArmed=false,inputUnlockAt=0;canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||performance.now()<inputUnlockAt){swipeArmed=false;return;}swipeArmed=true;sx=e.clientX;sy=e.clientY;});canvas.addEventListener('pointerup',e=>{if(!swipeArmed)return;swipeArmed=false;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<22)return;act(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});canvas.addEventListener('pointercancel',()=>{swipeArmed=false;});
function resize(){W=Math.min(innerWidth,560);H=innerHeight;renderer.setSize(W,H,false);camera.aspect=W/H;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
function loop(t){const raw=(t-last)/1000,dt=Number.isFinite(raw)?Math.min(.033,Math.max(0,raw)):0;last=t;if(qaMode&&state==='playing'){for(let i=0;i<8&&state==='playing';i++)update(dt);}else update(dt);renderer.render(scene,camera);requestAnimationFrame(loop);}buildWorld();hud();requestAnimationFrame(loop);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
